apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ingress
  namespace: wp-namespace
  labels:
    app: wordpress
spec:
  defaultBackend:
    service:
      name: wordpress
      port:
        number: 80