apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels: &labels # <- Reference pour ré-utiliser l'objet plus tard
    promo: b3c
    grade: b3
    type: td
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels: *labels # <- Utilisation de la référence
  strategy: {}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels: *labels # <- Utilisation de la référence
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim