apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    promo: b3c
    grade: b3
    type: td
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi