apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  labels:
    promo: b3c
    grade: b3
    type: td
spec:
  hard:
    limits.cpu: 500m
    limits.memory: 256Mi
    requests.cpu: 250m
    requests.memory: 128Mi