apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    promo: b3c
    grade: b3
    type: td
    app: hello-world
spec:
  selector: # Correspond au labels des pods à load-balancer
    app: hello-world
  ports:
    - name: http
      port: 8083
      targetPort: 3306
  type: ClusterIP # type par default